' Auto-generated by register-task.ps1 -- launches bridge-service.cmd hidden and
' waits for it, so Task Scheduler tracks the live supervisor and does not spawn
' competing copies on later triggers.
Option Explicit
Dim shell
Set shell = CreateObject("WScript.Shell")
shell.Run """C:\Users\OnyxB\AppData\Local\hermes\plugins\hermes-excel-sidecar\service\bridge-service.cmd""", 0, True
Set shell = Nothing
