<#
.SYNOPSIS
  Register (or unregister) the "Hermes_Excel_Bridge" logon-triggered Scheduled
  Task that runs the bridge supervisor per-user, hidden, with no elevation.

.DESCRIPTION
  requires elevation? NO. The task is registered in the current user's context
  and runs with the user's own (limited) token -- RunLevel = Limited. It is
  triggered at this user's logon and launches service\bridge-service.cmd via a
  hidden VBS shim so no console window appears.

  Idempotent: re-running re-registers (Register-ScheduledTask -Force). Pass
  -Unregister to remove the task.

.PARAMETER InstallDir
  Absolute install root. Default: %LOCALAPPDATA%\hermes\excel-addin

.PARAMETER DataDir
  HERMES_EXCEL_DATA_DIR (passed to the supervisor via its environment defaults).

.PARAMETER Port
  Bridge port baked into the launched run-bridge.cmd already; kept for parity.

.PARAMETER Unregister
  Remove the scheduled task instead of registering it.

.EXAMPLE
  powershell -ExecutionPolicy Bypass -File install\register-task.ps1
  powershell -ExecutionPolicy Bypass -File install\register-task.ps1 -Unregister
#>
[CmdletBinding()]
param(
  [string] $InstallDir = (Join-Path $env:LOCALAPPDATA 'hermes\excel-addin'),
  [string] $DataDir    = (Join-Path $env:LOCALAPPDATA 'hermes\excel-addin\data'),
  [int]    $Port       = 8787,
  [switch] $Unregister
)

$ErrorActionPreference = 'Stop'

# ---- Config block (retarget here) ------------------------------------------
$TaskName     = 'Hermes_Excel_Bridge'
$ServiceCmd   = Join-Path $InstallDir 'service\bridge-service.cmd'
# Launch the supervisor hidden via a generated VBS shim so no window flashes.
$ServiceVbs   = Join-Path $InstallDir 'service\bridge-service.vbs'
# ----------------------------------------------------------------------------

function Unregister-BridgeTask {
  $existing = Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue
  if ($existing) {
    try { Stop-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue } catch {}
    Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false
    Write-Host "[register-task] Unregistered scheduled task '$TaskName'."
  } else {
    Write-Host "[register-task] Task '$TaskName' not present; nothing to remove."
  }
}

if ($Unregister) {
  Unregister-BridgeTask
  return
}

try {
  if (-not (Test-Path -LiteralPath $ServiceCmd)) {
    throw "Supervisor not found at '$ServiceCmd'. Run addin-install.ps1 first."
  }

  # Generate the hidden VBS shim that launches the supervisor with no window.
  $vbs = @"
' Auto-generated by register-task.ps1 -- launches bridge-service.cmd hidden and
' waits for it, so Task Scheduler tracks the live supervisor and does not spawn
' competing copies on later triggers.
Option Explicit
Dim shell
Set shell = CreateObject("WScript.Shell")
shell.Run """$ServiceCmd""", 0, True
Set shell = Nothing
"@
  Set-Content -LiteralPath $ServiceVbs -Value $vbs -Encoding ASCII -Force

  # Action: wscript runs the VBS shim (hidden). Pass env via the action env is
  # not supported; the supervisor defaults DATA_DIR/INSTALL_DIR itself, but we
  # also set them here through cmd /c so an overridden install dir flows in.
  $action = New-ScheduledTaskAction -Execute 'wscript.exe' `
    -Argument "`"$ServiceVbs`"" `
    -WorkingDirectory $InstallDir

  # Trigger: at logon of the current user only.
  $trigger = New-ScheduledTaskTrigger -AtLogOn

  # Principal: current user, limited (no elevation), runs only when logged on.
  $principal = New-ScheduledTaskPrincipal -UserId ([System.Security.Principal.WindowsIdentity]::GetCurrent().Name) `
    -LogonType Interactive -RunLevel Limited

  $settings = New-ScheduledTaskSettingsSet `
    -AllowStartIfOnBatteries `
    -DontStopIfGoingOnBatteries `
    -StartWhenAvailable `
    -ExecutionTimeLimit ([TimeSpan]::Zero) `
    -RestartCount 3 -RestartInterval (New-TimeSpan -Minutes 1) `
    -Hidden

  # Idempotent (re)register.
  Register-ScheduledTask -TaskName $TaskName `
    -Action $action -Trigger $trigger -Principal $principal -Settings $settings `
    -Description "Hermes for Excel local bridge supervisor (per-user, hidden, no elevation). Port $Port." `
    -Force | Out-Null

  Write-Host "[register-task] Registered scheduled task '$TaskName' (logon-triggered, hidden, no elevation)."
}
catch {
  Write-Error "[register-task] FAILED: $($_.Exception.Message)"
  exit 1
}
